//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace matchManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int Id { get; set; }
        public int HomeTeamID { get; set; }
        public int VisitingTeamID { get; set; }
        public string Round { get; set; }
        public int StadiumId { get; set; }
        public int LeagueId { get; set; }
        public int SeasonId { get; set; }
        public Nullable<int> HomeTeamGoal { get; set; }
        public Nullable<int> VisitTeamGoal { get; set; }
        public string Referee { get; set; }
    
        public virtual League League { get; set; }
        public virtual Team Team { get; set; }
        public virtual Season Season { get; set; }
        public virtual Stadium Stadium { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
