//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace matchManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public int Age { get; set; }
        public int TeamID { get; set; }
        public string Nationality { get; set; }
        public string Position { get; set; }
        public string Picture { get; set; }
        public string Description { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
